apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Name }}
  labels:
    app: devops-logs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-logs
  template:
    metadata:
      labels:
        app: devops-logs
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command: ["/bin/sh"]
          args: ["-c", "/app/start.sh"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
