env:
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_BASIC_ENABLED: false
  GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 1m

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://devops-prometheus-kube-pro-prometheus:9090
     access: server
     orgId: 1
     isDefault: true
     basicAuth: false
     editable: false
   - name: Loki
     type: loki
     url: http://devops-loki-loki-distributed-gateway.grafana-loki.svc.cluster.local
     orgId: 1
     isDefault: false
     basicAuth: false
     editable: false

plugins: 
  - grafana-opensearch-datasource
