apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-logs
  name: python-logs-devops
  namespace: devops-logs
  annotations:
    description: "App python que gera logs para o Projeto DevOps."
    environment: "dev"
spec:
  selector:
    matchLabels:
      app: devops-logs
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-logs
    spec:
      containers:
      - command: ["/bin/sh"]
        args: ["-c", "/app/start.sh"]
        image: docker.io/janssenlima/projeto-devops:1.0
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        name: python-logs-devops
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: python-logs-devops
spec:
  selector:
    app: devops-logs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000